[graph]
all-features = true

[licenses]
confidence-threshold = 0.93
allow = [
    "0BSD",
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Zlib",
    "Unicode-3.0",
    "Unlicense",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []

[advisories]
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
